apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mykubernetes-92ce"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mykubernetes-92ce"
  template:
    metadata:
      labels:
        app: "mykubernetes-92ce"
    spec:
      containers:
        - name: "mykubernetes-92ce"
          image: "az304registry.azurecr.io/mykubernetes"
          ports:
          - containerPort: 5000