apiVersion: v1
kind: Service
metadata:
    name: "mykubernetes-92ce"
    labels:
        app: "mykubernetes-92ce"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "mykubernetes-92ce"