on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: az304registry.azurecr.io
        username: ${{ secrets.acr_az304registry_username }}
        password: ${{ secrets.acr_az304registry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t az304registry.azurecr.io/mykubernetes:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push az304registry.azurecr.io/mykubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mykubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mykubernetesadba | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mykubernetesadba`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mykubernetesadba
        container-registry-url: az304registry.azurecr.io
        container-registry-username: ${{ secrets.acr_az304registry_username }}
        container-registry-password: ${{ secrets.acr_az304registry_password }}
        secret-name: mykubernetesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mykubernetesadba
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          az304registry.azurecr.io/mykubernetes:${{ github.sha }}
        imagepullsecrets: |
          mykubernetesdockerauth
